version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo-1:27017/taskflow
      - CLIENT_URL=http://localhost:5173
      - PORT=5000
    depends_on:
      - mongo-1

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo-1:
    image: mongo:latest
    container_name: mongo-1
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
